version: '3.8'

services:
  nginx:
    container_name: psy-nexus-nginx
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-ssl.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-web:/var/www/certbot
      - certbot-certs:/etc/letsencrypt
      - frontend-dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
    networks:
      - psy-nexus-net

  certbot:
    container_name: psy-nexus-certbot
    image: certbot/certbot:latest
    volumes:
      - certbot-web:/var/www/certbot
      - certbot-certs:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    command: certonly --webroot --webroot-path=/var/www/certbot --email admin@psy-nexus.live --agree-tos --no-eff-email -d psy-nexus.live

volumes:
  certbot-web:
  certbot-certs:
  frontend-dist:
    external: true

networks:
  psy-nexus-net:
    external: true
