global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'librechat'
    static_configs:
      - targets: ['librechat:3080']
  - job_name: 'docker'
    static_configs:
      - targets: ['unix:///var/run/docker.sock']
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
